### ISSUE TITLE
Add configurable sections

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/release-notes-generator#6]
Currently the sections in the release notes are hardcoded.
It would be much better if we could set them in a configuration file.
We could use a YAML file like this:

```
sections:
  - new_features:
    title: "⭐ New Features"
    prefixes:
      - feature
      - features
  - bug_fixes:
    title: "🐞 Bug Fixes"
    prefixes:
      - fix
      - bugfix
  - other_changes:
    title: "💡Other Changes"
    prefixes:
      - other
      - chore
      - chores 
```
